# Generated by Django 5.0.6 on 2024-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_facebook_company_instagram_company_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.IntegerField(default=998901234567),
            preserve_default=False,
        ),
    ]
